Repository okta/terraform-provider-okta, pull requests merged in 2020-12, with the labels that each got.

#228 Overhaul idp_discovery_rule documentation
  website/docs/r/policy_rule_idp_discovery.html.markdown
Labels: documentation

#226 Add acs_endpoints to SAML app (okta_app_saml) definition
  examples/okta_app_saml/updated.tf
  okta/app.go
  okta/data_source_okta_app_saml.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_saml_test.go
  website/docs/d/app_saml.html.markdown
  website/docs/r/app_saml.html.markdown
Labels: enhancement

#238 Added missing attribute reference
  website/docs/r/app_saml.html.markdown
Labels: documentation

#242 Fixed user type by introducing state upgrader
  okta/config.go
  okta/provider_sweeper_test.go
  okta/resource_okta_app_user_base_schema.go
  okta/resource_okta_app_user_schema.go
  okta/resource_okta_user_base_schema.go
  okta/resource_okta_user_schema.go
  okta/resource_okta_user_type_test.go
  okta/user_schema.go
  okta/validators.go
Labels: bug, provider

#150 Check for exact group name match on group data source.
  okta/data_source_okta_group.go
Labels: size/XS

#245 Fixed documentation and several bugs
  CHANGELOG.md
  README.md
  okta/policy.go
  okta/resource_okta_app_bookmark.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_auth_server_policy_rule.go
  okta/resource_okta_policy_mfa.go
  okta/validators.go
  website/docs/r/app_basic_auth.html.markdown
  website/docs/r/app_bookmark.html.markdown
  website/docs/r/app_oauth.html.markdown
  website/docs/r/app_saml.html.markdown
  website/docs/r/auth_server_policy_rule.html.markdown
  website/docs/r/policy_rule_idp_discovery.html.markdown
Labels: bug, crash, documentation

#248 Added call recovery for Okta password policy
  examples/okta_policy_password/basic_updated.tf
  okta/resource_okta_auth_server.go
  okta/resource_okta_policy_password.go
  okta/resource_okta_policy_password_test.go
  website/docs/r/policy_password.html.markdown
Labels: documentation, enhancement

#251 Update data okta_group docs
  website/docs/d/group.html.markdown
Labels: documentation

#159 Adds "pattern" property for okta_user_schema and okta_user_base_schema.
  examples/okta_user_base_schema/basic.tf
  examples/okta_user_base_schema/basic_login.tf
  examples/okta_user_base_schema/login_updated.tf
  okta/resource_okta_app_user_base_schema.go
  okta/resource_okta_app_user_schema.go
  okta/resource_okta_user_base_schema.go
  okta/resource_okta_user_base_schema_test.go
  okta/resource_okta_user_schema.go
  okta/user_schema.go
  okta/utils.go
  sdk/user_schema_models.go
  website/docs/r/app_user_base_schema.html.markdown
  website/docs/r/user_base_schema.html.markdown
Labels: enhancement, size/S

#250 Invalid Rule Handling
  examples/okta_group/datasource_not_found.tf
  examples/okta_idp_social/basic.tf
  examples/okta_policy_rule_idp_discovery/basic_domain.tf
  okta/resource_okta_group_rule.go
  okta/resource_okta_group_rule_test.go
Labels: enhancement

#259 Allow dependabot to check go dependencies
  .github/dependabot.yml
Labels: dependencies

#262 Added retry for user custom resource create/update operations
  okta/resource_okta_policy_password.go
  okta/resource_okta_user_schema.go
  okta/resource_okta_user_schema_test.go
  okta/user_schema.go
Labels: bug

#263 Added 'max_clock_skew' to IdP SAML resource
  examples/okta_idp_saml/basic_updated.tf
  okta/resource_okta_idp_oidc.go
  okta/resource_okta_idp_saml.go
  okta/resource_okta_idp_saml_test.go
  okta/resource_okta_idp_social.go
  sdk/idp_models.go
  website/docs/r/idp_saml.html.markdown
Labels: enhancement

#271 Added usage to network zones
  examples/okta_network_zone/basic_updated.tf
  okta/resource_okta_network_zone.go
  okta/resource_okta_network_zone_test.go
  sdk/network_zone.go
  website/docs/r/network_zone.html.markdown
Labels: documentation, enhancement
