Repository okta/terraform-provider-okta, pull requests merged in 2020-05, with the labels that each got.

#18 Adding support for SMS template changes in Okta terraform plugin
  .gitignore
  examples/okta_template_sms/README.md
  examples/okta_template_sms/basic.tf
  examples/okta_template_sms/updated.tf
  okta/provider.go
  okta/resource_okta_template_sms.go
  okta/resource_okta_template_sms_test.go
  sdk/templates_sms.go
  website/docs/r/template_sms.html.markdown
  website/okta.erb
Labels: documentation, enhancement, size/XL

#15 Add user lockout notification channels
  examples/okta_policy_password/basic_updated.tf
  go.mod
  go.sum
  okta/resource_okta_policy_password.go
  okta/resource_okta_policy_password_test.go
  vendor/github.com/articulate/oktasdk-go/okta/policies.go
  vendor/modules.txt
  website/docs/r/policy_password.html.markdown
Labels: dependencies, documentation, enhancement, size/L

#121 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS
