Repository okta/terraform-provider-okta, pull requests merged in 2020-11, with the labels that each got.

#164 okta_app_auto_login enhancements
  examples/okta_app_auto_login/basic.tf
  examples/okta_app_auto_login/updated.tf
  okta/app.go
  okta/resource_okta_app_auto_login.go
  okta/resource_okta_app_auto_login_test.go
  okta/resource_okta_app_secure_password_store.go
  okta/resource_okta_app_swa.go
  okta/resource_okta_app_three_field.go
  okta/utils.go
  okta/utils_test.go
  website/docs/r/app_auto_login.html.markdown
Labels: enhancement

#156 Adds name to the error for group data call
  okta/data_source_okta_group.go
Labels: size/XS

#183 Adds User Types Support
  examples/okta_user_base_schema/non_default_user_type.tf
  examples/okta_user_schema/README.md
  examples/okta_user_schema/non_default_user_type.tf
  examples/okta_user_type/README.md
  examples/okta_user_type/datasource.tf
  examples/okta_user_type/okta_user_type.tf
  examples/okta_user_type/okta_user_type_updated.tf
  okta/config.go
  okta/data_source_okta_user_type.go
  okta/data_source_okta_user_type_test.go
  okta/provider.go
  okta/provider_test.go
  okta/resource_okta_user_base_schema.go
  okta/resource_okta_user_base_schema_test.go
  okta/resource_okta_user_schema.go
  okta/resource_okta_user_schema_test.go
  okta/resource_okta_user_type.go
  okta/resource_okta_user_type_test.go
  okta/user_schema.go
  okta/user_type.go
  sdk/user_schema.go
  website/docs/d/user_type.html.markdown
  website/docs/r/user_base_schema.html.markdown
  website/docs/r/user_schema.html.markdown
  website/docs/r/user_type.html.markdown
Labels: enhancement, new-resource, size/XL
