Repository okta/terraform-provider-okta, pull requests merged in 2020-08, with the labels that each got.

#169 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation, size/XS

#102 Add external_namespace property for app_user_schema and user_schema
  okta/user_schema.go
  sdk/user_schema_models.go
  website/docs/r/app_user_schema.html.markdown
  website/docs/r/user_schema.html.markdown
Labels: bug, documentation, enhancement, size/M

#168 Add password import inline hook type
  examples/okta_inline_hook/password_import.tf
  okta/resource_okta_inline_hooks.go
  okta/resource_okta_inline_hooks_test.go
Labels: enhancement, size/S

#175 Fix inline hook example code to match version that is supported
  website/docs/r/inline_hook.html.markdown
Labels: documentation

#165 Update app_group_assignment.html.markdown
  website/docs/r/app_group_assignment.html.markdown
Labels: documentation
