Repository okta/terraform-provider-okta, pull requests merged in 2020-10, with the labels that each got.

#173 documentation update: okta_idp_metadata_saml correct example
  website/docs/d/idp_metadata_saml.html.markdown
Labels: bug, documentation, size/XS

#172 Update warning in app_group_assignment.html.markdown
  website/docs/r/app_group_assignment.html.markdown
Labels: documentation, size/XS

#192 Update config.go
  okta/config.go
Labels: enhancement, size/XS

#196 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#147 Fix validation false positive when api_token is set via environment variable
  okta/provider.go
Labels: enhancement, size/XS

#207 Update config.go
  okta/config.go
Labels: enhancement

#208 Update required to optional and more
  okta/provider.go
  website/docs/index.html.markdown
Labels: documentation, enhancement

#209 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
