Repository okta/terraform-provider-okta, pull requests merged in 2020-07, with the labels that each got.

#138 Adding support for GROUP_MEMBERSHIP_ADMIN & REPORT_ADMIN
  examples/okta_group_roles/all_roles.tf
  okta/resource_okta_group_roles_test.go
  sdk/group_role.go
  website/docs/r/group_roles.html.markdown
Labels: dependencies, documentation, size/XS

#126 Fixed provider_id typo in okta_factor in web documentation
  website/docs/r/factor.html.markdown
Labels: documentation, size/XS

#127 Fix terraform import command for okta_mfa_policy
  website/docs/r/policy_mfa.html.markdown
Labels: documentation, size/XS

#151 Update app_oauth.html.markdown
  website/docs/r/app_oauth.html.markdown
Labels: documentation, size/XS

#160 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#161 Fix due to Hashicorp CI/CD expecting particular CHANGLOG format
  CHANGELOG.md
Labels: size/XS
