Repository okta/terraform-provider-okta, pull requests merged in 2021-03, with the labels that each got.

#358 Removed redundant method
  README.md
  okta/data_source_okta_user_profile_mapping_source.go
  sdk/api_supplement.go
  sdk/mappings.go
Labels: enhancement

#360 Added new formatting tool, remove unused dep
  GNUmakefile
  go.mod
  go.sum
Labels: enhancement

#362 Removed 'ForceNew' in case policy name changes
  .github/CONTRIBUTING.md
  .github/MAINTAINING.md
  .goreleaser.yml
  README.md
  examples/okta_policy_mfa/basic_updated.tf
  examples/okta_user_schema/README.md
  go.mod
  go.sum
  main.go
  okta/config.go
  okta/data_source_okta_app_oauth_test.go
  okta/data_source_okta_app_saml_test.go
  okta/data_source_okta_app_test.go
  okta/data_source_okta_auth_server_test.go
  okta/data_source_okta_default_policy.go
  okta/data_source_okta_default_policy_test.go
  okta/data_source_okta_policy.go
  okta/data_source_okta_policy_test.go
  okta/policy.go
  okta/policy_rule.go
  okta/provider_sweeper_test.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_user_test.go
  okta/resource_okta_auth_server_policy.go
  okta/resource_okta_auth_server_policy_rule.go
  okta/resource_okta_factor.go
  okta/resource_okta_idp_oidc_test.go
  okta/resource_okta_idp_saml_test.go
  okta/resource_okta_network_zone.go
  okta/resource_okta_network_zone_test.go
  okta/resource_okta_policy_mfa.go
  okta/resource_okta_policy_mfa_test.go
  okta/resource_okta_policy_password.go
  okta/resource_okta_policy_password_test.go
  okta/resource_okta_policy_rule_idp_discovery.go
  okta/resource_okta_policy_rule_idp_discovery_test.go
  okta/resource_okta_policy_rule_mfa.go
  okta/resource_okta_policy_rule_mfa_test.go
  okta/resource_okta_policy_rule_password.go
  okta/resource_okta_policy_rule_password_test.go
  okta/resource_okta_policy_rule_sign_on.go
  okta/resource_okta_policy_rule_sign_on_test.go
  okta/resource_okta_policy_sign_on.go
  okta/resource_okta_policy_sign_on_test.go
  okta/resource_okta_profile_mapping.go
  okta/resource_okta_template_email.go
  okta/resource_okta_template_sms.go
  okta/resource_okta_user_base_schema.go
  okta/resource_okta_user_schema.go
  okta/user_schema.go
  okta/utils.go
  website/docs/index.html.markdown
Labels: enhancement

#363 Added hotp factor to the Okta MFA policy
  examples/okta_policy_mfa/basic_updated.tf
  okta/resource_okta_factor.go
  okta/resource_okta_policy_mfa.go
  okta/resource_okta_policy_mfa_test.go
  sdk/factor.go
  sdk/policy.go
  website/docs/r/policy_mfa.html.markdown
Labels: enhancement

#366 Fixed error handler
  okta/config.go
  okta/resource_okta_app_saml.go
Labels: crash

#372 Removed validation for `login_uri`
  okta/resource_okta_app_oauth.go
Labels: bug

#375 Added new `okta_auth_server_default` resource
  examples/okta_auth_server_default/basic.tf
  examples/okta_auth_server_default/basic_updated.tf
  go.mod
  go.sum
  okta/provider.go
  okta/resource_okta_default_auth_server.go
  okta/resource_okta_default_auth_server_test.go
  website/docs/r/auth_server_default.html.markdown
Labels: new-resource

#376 Fixed default auth server and minor refactoring
  examples/okta_auth_server_default/basic.tf
  examples/okta_auth_server_default/basic_updated.tf
  okta/app.go
  okta/data_source_okta_app.go
  okta/data_source_okta_app_oauth.go
  okta/data_source_okta_app_saml.go
  okta/data_source_okta_group.go
  okta/fixtures.go
  okta/provider.go
  okta/resource_okta_admin_role_targets_test.go
  okta/resource_okta_app_group_assignment_test.go
  okta/resource_okta_app_oauth_api_scope.go
  okta/resource_okta_app_oauth_api_scope_test.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_user_base_schema_test.go
  okta/resource_okta_app_user_test.go
  okta/resource_okta_default_auth_server.go
  okta/resource_okta_default_auth_server_test.go
  okta/resource_okta_group_membership.go
  okta/resource_okta_group_role.go
  okta/resource_okta_group_rule.go
  okta/resource_okta_user_test.go
Labels: bug, enhancement

#381 Fix group assignment priority
  examples/okta_app_group_assignment/basic.tf
  examples/okta_app_group_assignment/updated.tf
  go.mod
  go.sum
  okta/resource_okta_app_group_assignment.go
  okta/resource_okta_app_group_assignment_test.go
Labels: bug

#392 Added new 'auth_server_claim_default' resource
  examples/okta_auth_server_claim_default/README.md
  examples/okta_auth_server_claim_default/basic.tf
  okta/provider.go
  okta/resource_okta_auth_server_claim.go
  okta/resource_okta_auth_server_claim_default.go
  okta/resource_okta_auth_server_claim_default_test.go
  website/docs/r/auth_server_claim.html.markdown
  website/docs/r/auth_server_claim_default.html.markdown
Labels: new-resource

#386 Fixed status change for auth server policy rule
  okta/resource_okta_auth_server_policy_rule.go
  sdk/authorization_server_policy_rules.go
Labels: bug

#388 Added possibility to remove users assigned by this rule after deleting the rule
  okta/resource_okta_group_rule.go
  website/docs/r/group_rule.html.markdown
Labels: enhancement

#390 Added retry to okta_group_role resource
  okta/resource_okta_group_role.go
Labels: enhancement

#397 Added validator to 'okta_policy_rule_idp_discovery'
  .goreleaser.yml
  okta/resource_okta_policy_rule_idp_discovery.go
  website/docs/r/policy_rule_idp_discovery.html.markdown
Labels: enhancement

#395 Added groups and users to app* data sources
  go.mod
  go.sum
  okta/app.go
  okta/data_source_okta_app.go
  okta/data_source_okta_app_oauth.go
  okta/data_source_okta_app_saml.go
  okta/data_source_okta_group.go
  okta/data_source_okta_idp_social.go
  okta/group.go
  okta/resource_okta_admin_role_targets.go
  website/docs/d/app.html.markdown
  website/docs/d/app_metadata_saml.html.markdown
  website/docs/d/app_oauth.html.markdown
  website/docs/d/app_saml.html.markdown
  website/docs/d/everyone_group.html.markdown
  website/docs/d/group.html.markdown
Labels: enhancement

#103 add data.okta_groups for listing groups
  examples/okta_groups/datasource.tf
  examples/okta_groups/okta_groups.tf
  go.sum
  okta/data_source_okta_group.go
  okta/data_source_okta_groups.go
  okta/data_source_okta_groups_test.go
  okta/group.go
  okta/provider.go
  website/docs/d/groups.html.markdown
Labels: documentation, new-data-source, size/M

#399 Added CHANGELOG for 3.11.0
  CHANGELOG.md
  go.sum
  website/docs/d/user_type.html.markdown
  website/docs/index.html.markdown
  website/docs/r/app_oauth_api_scope.html.markdown
  website/docs/r/group_membership.html.markdown
  website/okta.erb
Labels: documentation
