Repository okta/terraform-provider-okta, pull requests merged in 2021-02, with the labels that each got.

#320 Fixed 'subject_match_attribute' setup
  okta/idp.go
  okta/resource_okta_idp_saml.go
Labels: bug

#323 Fixed users when doing group import
  okta/resource_okta_group.go
Labels: bug

#325 New resource `okta_admin_role_targets`
  examples/okta_admin_role_targets/README.md
  examples/okta_admin_role_targets/basic.tf
  examples/okta_admin_role_targets/updated.tf
  okta/provider.go
  okta/resource_okta_admin_role_targets.go
  okta/resource_okta_admin_role_targets_test.go
  okta/resource_okta_user.go
  okta/utils.go
  sdk/user_role.go
  website/docs/r/admin_role_targets.html.markdown
Labels: new-resource

#328 Custom swa app
  go.mod
  go.sum
  okta/resource_okta_app_swa.go
Labels: bug

#331 Force 'okta_app_user_schema' resource recreate when changing scope
  examples/okta_user_schema/basic.tf
  examples/okta_user_schema/updated.tf
  okta/provider_sweeper_test.go
  okta/provider_test.go
  okta/resource_okta_app_group_assignment.go
  okta/resource_okta_app_user.go
  okta/resource_okta_app_user_base_schema.go
  okta/resource_okta_app_user_schema.go
  okta/resource_okta_group_membership.go
  okta/resource_okta_group_membership_test.go
  okta/resource_okta_group_role.go
  okta/resource_okta_profile_mapping.go
  okta/resource_okta_user_base_schema_test.go
  okta/resource_okta_user_schema.go
  okta/resource_okta_user_schema_test.go
  okta/user.go
  okta/user_schema.go
  sdk/mappings.go
Labels: bug

#332 Fix 'terraform plan' in case delete_when_absent is set to 'false'
  okta/resource_okta_profile_mapping.go
Labels: bug

#333 Fixed validation for 'login_mode' and 'login_scopes'
  go.mod
  go.sum
  okta/resource_okta_app_oauth.go
Labels: bug

#336 Added okta_auth_server_scopes datasource
  examples/okta_auth_server_scope/README.md
  examples/okta_auth_server_scopes/README.md
  examples/okta_auth_server_scopes/datasource.tf
  go.sum
  okta/data_source_okta_auth_server_scopes.go
  okta/data_source_okta_auth_server_scopes_test.go
  okta/provider.go
  website/docs/d/auth_server_scopes.html.markdown
Labels: new-data-source

#337 Added social IdP data source
  examples/okta_idp_social/datasource.tf
  okta/data_source_okta_idp_social.go
  okta/data_source_okta_idp_social_test.go
  okta/provider.go
  okta/resource_okta_idp_social.go
  website/docs/d/idp_social.html.markdown
Labels: new-data-source

#338 Fixed error handling
  okta/data_source_okta_idp_social.go
Labels: bug

#340 Moved validation for `okta_app_oauth` out of `CustomizeDiff` func
  okta/resource_okta_app_oauth.go
Labels: bug

#341 Fixed group role when removing all the items from target_group_list
  okta/resource_okta_group_role.go
Labels: bug

#342 Added retry for role re-assignment
  okta/app.go
  okta/config.go
  okta/resource_okta_admin_role_targets.go
  okta/resource_okta_group.go
  okta/resource_okta_group_membership.go
  okta/utils.go
Labels: enhancement

#344 Fixed set of `subject_match_attribute` value for `okta_idp_oidc` resource
  okta/resource_okta_idp_oidc.go
  okta/resource_okta_idp_saml.go
Labels: bug

#335 Okta Group Membership - Wait after create
  okta/resource_okta_group_membership.go
Labels: enhancement, waiting-response

#330 Retain user group app assignments
  examples/okta_app_group_assignment/retain_assignment.tf
  examples/okta_app_group_assignment/retain_assignment_destroy.tf
  examples/okta_app_user/retain.tf
  examples/okta_app_user/retain_destroy.tf
  okta/resource_okta_app_group_assignment.go
  okta/resource_okta_app_group_assignment_test.go
  okta/resource_okta_app_user.go
  okta/resource_okta_app_user_test.go
  okta/test_utils.go
  website/docs/r/app_group_assignment.html.markdown
  website/docs/r/app_user.html.markdown
Labels: needs-investigation, waiting-response

#348 Fixed validation for several resources
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_swa.go
  okta/resource_okta_app_user_base_schema.go
  okta/resource_okta_app_user_schema.go
  okta/resource_okta_auth_server_policy_rule.go
  okta/resource_okta_group_membership.go
  okta/resource_okta_network_zone.go
  okta/resource_okta_user_base_schema.go
Labels: bug

#349 Added 'target_app_list' to the 'okta_group_role' resource
  examples/okta_group_role/basic.tf
  examples/okta_group_role/group_targets.tf
  examples/okta_group_role/group_targets_removed.tf
  examples/okta_group_role/group_targets_updated.tf
  okta/resource_okta_admin_role_targets.go
  okta/resource_okta_group_role.go
  okta/resource_okta_group_role_test.go
  website/docs/r/group_role.html.markdown
Labels: enhancement

#351 Added 'OVERRIDE' master property
  okta/resource_okta_app_user_base_schema.go
  okta/resource_okta_app_user_schema.go
  okta/resource_okta_user_base_schema.go
  okta/resource_okta_user_schema.go
  okta/user_schema.go
  okta/utils.go
  sdk/user_schema.go
  website/docs/r/user_schema.html.markdown
Labels: enhancement

#352 Fixed setup for default scope
  go.mod
  go.sum
  okta/config.go
  okta/resource_okta_app_oauth.go
Labels: bug
