Repository okta/terraform-provider-okta, pull requests merged in 2021-08, with the labels that each got.

#559 Updated Okta Golang SDK
  go.mod
  go.sum
  okta/resource_okta_auth_server_policy.go
  okta/resource_okta_group_rule.go
  okta/resource_okta_group_rule_test.go
Labels: dependencies

#556 Request governor for Okta Management API calls
  okta/config.go
  okta/internal/apimutex/apimutex.go
  okta/internal/apimutex/apimutex_test.go
  okta/internal/transport/governed_transport.go
  okta/internal/transport/governed_transport_test.go
  okta/provider.go
  website/docs/index.html.markdown
Labels: enhancement

#565 Fixed users and groups assignment in the apps, minor refactoring
  okta/app.go
  okta/config.go
  okta/data_source_okta_app.go
  okta/data_source_okta_app_oauth.go
  okta/data_source_okta_app_saml.go
  okta/data_source_okta_behavior.go
  okta/data_source_okta_idp_social.go
  okta/fixtures_test.go
  okta/group.go
  okta/internal/apimutex/apimutex.go
  okta/internal/apimutex/apimutex_test.go
  okta/internal/transport/governed_transport.go
  okta/internal/transport/governed_transport_test.go
  okta/provider.go
  okta/provider_sweeper_test.go
  okta/provider_test.go
  okta/resource_okta_app_user_schema_property.go
  okta/resource_okta_group_role.go
  okta/resource_okta_user_base_schema_property.go
  okta/resource_okta_user_base_schema_property_test.go
  okta/resource_okta_user_schema_property.go
  okta/resource_okta_user_schema_property_test.go
  okta/utils.go
  okta/utils_for_test.go
  okta/utils_test.go
  sdk/api_supplement.go
  sdk/app_logo.go
  sdk/app_oauth_group_claim.go
  sdk/app_user_schema.go
  sdk/authorization_server_policy.go
  sdk/authorization_server_policy_rules.go
  sdk/behavior.go
  sdk/domain.go
  sdk/factor_hotp.go
  sdk/idp_discovery_rule.go
  sdk/mappings.go
  sdk/metadata.go
  sdk/network_zone.go
  sdk/org_factor.go
  sdk/policy.go
  sdk/policy_rule.go
  sdk/templates_email.go
  sdk/templates_sms.go
  sdk/user_factor.go
  sdk/user_role.go
  sdk/user_schema.go
Labels: bug, enhancement

#567 Substituted some of the internal SDK methods with official ones
  go.mod
  go.sum
  okta/config.go
  okta/provider_sweeper_test.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_user_base_schema_property.go
  okta/resource_okta_app_user_custom_schema_property.go
  okta/resource_okta_app_user_custom_schema_property_test.go
  okta/resource_okta_auth_server_policy.go
  okta/resource_okta_auth_server_policy_rule.go
  okta/resource_okta_domain.go
  okta/resource_okta_domain_test.go
  okta/resource_okta_network_zone.go
  okta/resource_okta_network_zone_test.go
  okta/resource_okta_template_sms.go
  okta/resource_okta_user_base_schema_property.go
  okta/resource_okta_user_base_schema_property_test.go
  okta/resource_okta_user_custom_schema_property.go
  okta/resource_okta_user_custom_schema_property_test.go
  okta/user_schema.go
  okta/user_type.go
  okta/utils.go
  sdk/app_user_schema.go
  sdk/authorization_server_policy.go
  sdk/authorization_server_policy_rules.go
  sdk/domain.go
  sdk/network_zone.go
  sdk/templates_sms.go
  sdk/user_schema.go
  website/docs/r/user_base_schema_property.html.markdown
Labels: enhancement

#571 Added AuthTransport for handling auth errors
  go.mod
  go.sum
  okta/config.go
  okta/internal/transport/auth.go
  okta/internal/transport/governed_transport.go
  okta/provider.go
Labels: enhancement

#583 Fixed okta_user_schema_property
  go.mod
  go.sum
  okta/provider_test.go
  okta/user_schema.go
Labels: bug

#586 Fixed network zone
  go.mod
  go.sum
  okta/resource_okta_app_user_base_schema_property.go
  okta/resource_okta_network_zone.go
  okta/resource_okta_template_sms_test.go
  okta/resource_okta_user_base_schema_property.go
  okta/resource_okta_user_custom_schema_property_test.go
  okta/user_schema.go
Labels: bug

#589 Add 'admin_note' and 'enduser_note' to all app* resources
  examples/okta_app_auto_login/basic.tf
  examples/okta_app_auto_login/updated.tf
  go.mod
  go.sum
  okta/app.go
  okta/app_filter.go
  okta/app_test.go
  okta/config.go
  okta/data_source_okta_app.go
  okta/max_api_capacity_test.go
  okta/resource_okta_app_auto_login.go
  okta/resource_okta_app_auto_login_test.go
  okta/resource_okta_app_basic_auth.go
  okta/resource_okta_app_bookmark.go
  okta/resource_okta_app_oauth.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_secure_password_store.go
  okta/resource_okta_app_shared_credentials.go
  okta/resource_okta_app_swa.go
  okta/resource_okta_app_three_field.go
  okta/resource_okta_template_sms.go
  okta/utils.go
  website/docs/r/app_auto_login.html.markdown
  website/docs/r/app_basic_auth.html.markdown
  website/docs/r/app_bookmark.html.markdown
  website/docs/r/app_oauth.html.markdown
  website/docs/r/app_saml.html.markdown
  website/docs/r/app_swa.html.markdown
  website/docs/r/app_three_field.html.markdown
Labels: enhancement

#592 Fixed sms template translations
  okta/resource_okta_template_sms.go
Labels: bug

#593 Add 'saml_version' to the 'okta_app_saml' resource
  examples/okta_app_saml/import_saml_1_1.tf
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_saml_test.go
  website/docs/r/app_saml.html.markdown
Labels: enhancement

#599 Add 'asns' field to the 'okta_network_zone' resource
  examples/okta_network_zone/basic_updated.tf
  okta/app.go
  okta/data_source_okta_app.go
  okta/data_source_okta_app_group_assignments.go
  okta/data_source_okta_app_oauth.go
  okta/data_source_okta_app_saml.go
  okta/data_source_okta_app_user_assignments.go
  okta/data_source_okta_auth_server.go
  okta/data_source_okta_auth_server_policy.go
  okta/data_source_okta_group.go
  okta/data_source_okta_idp_oidc.go
  okta/data_source_okta_idp_saml.go
  okta/data_source_okta_idp_social.go
  okta/policy.go
  okta/policy_rule.go
  okta/resource_okta_admin_role_targets.go
  okta/resource_okta_app_oauth.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_auth_server.go
  okta/resource_okta_auth_server_claim.go
  okta/resource_okta_auth_server_claim_default.go
  okta/resource_okta_auth_server_policy.go
  okta/resource_okta_auth_server_policy_rule.go
  okta/resource_okta_default_auth_server.go
  okta/resource_okta_group.go
  okta/resource_okta_group_roles.go
  okta/resource_okta_group_rule.go
  okta/resource_okta_idp_oidc.go
  okta/resource_okta_idp_saml.go
  okta/resource_okta_idp_saml_key.go
  okta/resource_okta_idp_social.go
  okta/resource_okta_network_zone.go
  okta/resource_okta_network_zone_test.go
  okta/resource_okta_policy_password.go
  okta/resource_okta_policy_password_default.go
  okta/resource_okta_policy_rule_sign_on.go
  okta/utils.go
  website/docs/r/network_zone.html.markdown
Labels: enhancement

#602 Add 'app_settings_json' to the 'okta_app_auto_login' resource
  okta/resource_okta_app_auto_login.go
  website/docs/r/app_auto_login.html.markdown
Labels: enhancement

#616 Fixed nil pointers when importing Okta Workflows
  okta/app.go
  okta/policy_rule.go
  okta/resource_okta_app_oauth.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_shared_credentials.go
  okta/resource_okta_policy_mfa.go
Labels: bug

#617 Bumped SDK and Golang version
  go.mod
  go.sum
  okta/config.go
  okta/resource_okta_admin_role_targets.go
  okta/resource_okta_app_swa.go
  okta/user_test.go
  sdk/user_role.go
  tools.go
Labels: dependencies

#619 Added missing fields to the `okta_app_three_field` resource
  examples/okta_app_three_field/updated_credentials.tf
  okta/resource_okta_app_three_field.go
  okta/resource_okta_app_three_field_test.go
  okta/utils_for_test.go
  website/docs/r/app_secure_password_store.html.markdown
  website/docs/r/app_three_field.html.markdown
Labels: enhancement

#622 Add `password_hash` to the `okta_user` resource
  examples/okta_user/all_attributes.tf
  examples/okta_user/custom_attributes.tf
  examples/okta_user/custom_attributes_array.tf
  examples/okta_user/password_hash.tf
  examples/okta_user/password_hash_updated.tf
  examples/okta_user/remove_custom_attributes.tf
  examples/okta_user/staged.tf
  okta/app.go
  okta/data_source_okta_app_saml.go
  okta/policy_rule.go
  okta/resource_okta_app_group_assignments.go
  okta/resource_okta_domain.go
  okta/resource_okta_policy_rule_idp_discovery.go
  okta/resource_okta_user.go
  okta/resource_okta_user_admin_roles_test.go
  okta/resource_okta_user_test.go
  okta/user_schema.go
  okta/utils.go
  sdk/idp_discovery_rule.go
  website/docs/r/app_user_schema.html.markdown
  website/docs/r/user.html.markdown
  website/docs/r/user_schema.html.markdown
Labels: enhancement
