Repository okta/terraform-provider-okta, pull requests merged in 2021-12, with the labels that each got.

#842 Added missing fields for Apple IdP
  go.mod
  go.sum
  okta/resource_okta_idp_social.go
  website/docs/r/idp_social.html.markdown
Labels: enhancement

#848 Fixed docs
  okta/resource_okta_domain_certificate.go
  website/docs/r/app_oauth_redirect_uri.html.markdown
  website/docs/r/domain_certificate.html.markdown
Labels: documentation, enhancement

#852 Updated Golang SDK
  go.mod
  go.sum
Labels: dependencies

#851 Support Custom Group Profile Schema
  examples/okta_group/okta_group_custom_base.tf
  examples/okta_group/okta_group_custom_removal.tf
  examples/okta_group/okta_group_custom_updated.tf
  okta/resource_okta_group.go
  okta/resource_okta_group_test.go
  website/docs/r/group.html.markdown
Labels: enhancement

#855 Fixed docs
  website/docs/r/idp_social.html.markdown
Labels: documentation
