Repository okta/terraform-provider-okta, pull requests merged in 2021-01, with the labels that each got.

#118 fix(user): ignore special groups (BUILT_IN and APP_GROUP) in the group_memberships field
  okta/user.go
Labels: needs-investigation, size/XS

#278 Removed redundant 'description' field
  okta/app.go
  okta/app_filter.go
  okta/data_source_okta_app.go
  okta/data_source_okta_app_saml.go
  okta/resource_okta_app_saml.go
  website/docs/d/app.html.markdown
  website/docs/d/app_saml.html.markdown
  website/docs/r/app_saml.html.markdown
Labels: bug, documentation, size/S

#128 Saml metadata fixes
  okta/app_filter.go
  okta/data_source_okta_app_saml_metadata.go
  sdk/api_supplement.go
  website/docs/d/app_metadata_saml.html.markdown
Labels: needs-investigation, size/XS

#283 Fixed system claims delete process
  okta/resource_okta_auth_server_claim.go
Labels: bug

#284 Fixed group membership populating
  okta/data_source_okta_user.go
  okta/user.go
Labels: bug

#285 Added retry on 404 error
  okta/app.go
  okta/config.go
  okta/data_source_okta_auth_server.go
  okta/resource_okta_auth_server.go
  okta/resource_okta_auth_server_claim.go
  okta/resource_okta_auth_server_policy.go
  okta/resource_okta_auth_server_policy_rule.go
  okta/resource_okta_auth_server_scope.go
  okta/resource_okta_auth_server_test.go
  okta/resource_okta_group.go
  sdk/authorization_server_claims.go
  sdk/authorization_server_policies.go
  sdk/authorization_server_policy_rules.go
  sdk/authorization_server_scopes.go
  sdk/authorization_servers.go
  sdk/templates_email.go
Labels: dependencies

#288 Fixed documentation and several issues
  okta/data_source_okta_users.go
  okta/resource_okta_inline_hooks.go
  okta/resource_okta_user.go
  website/docs/r/app_saml.html.markdown
  website/docs/r/idp_saml_signing_key.html.markdown
  website/docs/r/user.html.markdown
Labels: bug, documentation

#289 Updated okta-sdk-golang to v2.2.2
  go.mod
  go.sum
Labels: dependencies

#290 Added several features, refactored some code, fixed app related bugs
  go.mod
  go.sum
  okta/app_filter.go
  okta/app_test.go
  okta/config.go
  okta/data_source_okta_app.go
  okta/data_source_okta_app_saml.go
  okta/data_source_okta_app_saml_metadata.go
  okta/data_source_okta_idp_metadata_saml.go
  okta/data_source_okta_users.go
  okta/provider.go
  okta/provider_sweeper_test.go
  okta/provider_test.go
  okta/resource_okta_app_saml.go
  okta/test.json
  okta/test_utils.go
  sdk/api_supplement.go
  sdk/metadata.go
  website/docs/index.html.markdown
Labels: enhancement, technical-debt

#291 Added `union` attribute to `okta_app_user_schema`
  okta/resource_okta_app_user_base_schema.go
  okta/resource_okta_app_user_schema.go
  okta/user_schema.go
  website/docs/r/app_user_schema.html.markdown
Labels: enhancement

#293 Added 'okta_app_oauth' datasource
  examples/okta_app_oauth/datasource.tf
  okta/app.go
  okta/data_source_okta_app_oauth.go
  okta/data_source_okta_app_oauth_test.go
  okta/provider.go
Labels: new-data-source

#296 Suppress diff for 'features'
  okta/resource_okta_app_saml.go
  website/docs/r/app_saml.html.markdown
Labels: no-api

#297 Added missing argument reference for `okta_app_saml`
  website/docs/r/app_saml.html.markdown
Labels: documentation

#120 Expose Implicit Assignment [Federation Broker] setting of okta_app_oauth resource
  .github/CONTRIBUTING.md
  .github/MAINTAINING.md
  README.md
  examples/README.md
  examples/okta_app_basic_auth/basic.tf
  examples/okta_app_oauth/README.md
  examples/okta_app_oauth/federation_broker_off.tf
  examples/okta_app_oauth/federation_broker_on.tf
  examples/okta_app_saml/README.md
  examples/okta_auth_server_policy_rule/README.md
  examples/okta_group/README.md
  examples/okta_trusted_origin/README.md
  examples/okta_user/README.md
  okta/data_source_okta_auth_server.go
  okta/resource_okta_app_oauth.go
  okta/resource_okta_app_oauth_test.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_user_test.go
  okta/user_schema.go
  sdk/app_oidc_models.go
  website/docs/r/app_oauth.html.markdown
Labels: documentation, early-access, enhancement, size/M

#299 Fixed auth server policy status change
  okta/policy.go
  okta/resource_okta_auth_server_policy.go
  sdk/authorization_server_policy.go
Labels: bug

#300 Validators
  okta/data_source_okta_app_oauth.go
  okta/idp.go
  okta/resource_okta_app_bookmark.go
  okta/resource_okta_app_oauth.go
  okta/resource_okta_app_oauth_redirect_uri.go
  okta/resource_okta_auth_server_policy.go
  okta/resource_okta_idp_oidc.go
  okta/resource_okta_idp_saml.go
  okta/resource_okta_user.go
Labels: enhancement

#301 Added `issuer` and `issuer_mode` fields to the `okta_auth_server`
  .github/workflows/stale.yml
  okta/data_source_okta_auth_server.go
  okta/data_source_okta_auth_server_test.go
  okta/resource_okta_auth_server.go
  website/docs/d/auth_server.html.markdown
Labels: enhancement

#302 Added diff check for oauth app
  okta/resource_okta_app_oauth.go
Labels: bug

#309 Fixed user_name_template_* fields setup for apps
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_swa.go
Labels: bug

#307 Added SLO to the app SAML resource
  examples/okta_app_saml/basic.tf
  go.mod
  go.sum
  okta/app.go
  okta/data_source_okta_app_saml.go
  okta/resource_okta_app_saml.go
  okta/resource_okta_app_saml_test.go
  website/docs/d/app_saml.html.markdown
  website/docs/r/app_saml.html.markdown
Labels: enhancement

#311 Added login_mode and login_scopes to the `app_oauth`
  okta/data_source_okta_app_oauth.go
  okta/resource_okta_app_oauth.go
  okta/resource_okta_app_oauth_test.go
  okta/resource_okta_template_email.go
  website/docs/r/app_oauth.html.markdown
Labels: enhancement

#314 Fixed 'refresh_token_window_minutes' min value
  okta/resource_okta_auth_server_policy_rule.go
  website/docs/r/auth_server_policy_rule.html.markdown
Labels: enhancement

#313 Fixed 'attribute_statements' validation
  examples/okta_app_saml/datasource.tf
  okta/app.go
  okta/data_source_okta_app_saml.go
  okta/data_source_okta_app_saml_test.go
  okta/resource_okta_app_saml.go
  website/docs/d/app_saml.html.markdown
  website/docs/r/app_saml.html.markdown
Labels: bug, enhancement

#252 New Resource: Okta Group Membership
  examples/okta_group_membership/README.md
  examples/okta_group_membership/okta_group_membership.tf
  examples/okta_group_membership/okta_group_membership_updated.tf
  okta/provider.go
  okta/resource_okta_group_membership.go
  okta/resource_okta_group_membership_test.go
  website/docs/r/group_membership.html.markdown
Labels: new-resource

#316 Added 'metadata_url' to the 'okta_app_saml' resource
  okta/resource_okta_app_saml.go
  website/docs/r/app_saml.html.markdown
Labels: enhancement

#255 New Resource: okta_group_role
  examples/okta_group_role/README.md
  examples/okta_group_role/basic.tf
  okta/provider.go
  okta/resource_okta_group_role.go
  okta/resource_okta_group_role_test.go
  okta/resource_okta_group_roles.go
  website/docs/r/group_role.html.markdown
Labels: new-resource
